### ISSUE TITLE
ADO.NET empty Designer.cs

### ISSUE THREAD

**Issue by alibekp** [alibekp/site#1]
Hello!
In Visual Studio 2017 version 15.7.4 i have asp.net project with PostgresQL database. When i making  ADO.NET Entity Data Model with PostgresQL it makes .edmx[Diagram] object correctly, but showng nothing in MyModel.Designer.cs:

// T4 code generation is enabled for model 'C:\Users\User\Desktop\Alibek1\Alibek1\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.
  
   When i'm clicking Generate Database from Model in my Model1.edmx it shows error:
![image](https://user-images.githubusercontent.com/31817804/43816466-c1ec072e-9af6-11e8-9c46-b2be6bdf081a.png)

    Here's some parts of my Web.config:
`configuration>
  <configSections>
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
    
  </configSections>
  <connectionStrings>
    <add name="DefaultConnection" connectionString="Server=localhost;user id=postgres;password=123;database=postgres;" providerName="Npgsql" /><add name="Model1" connectionString="Host=localhost;Database=postgres;Username=postgres;Persist Security Info=True;Password=123" providerName="Npgsql" /><add name="postgresEntities" connectionString="metadata=res://*/Model1.csdl|res://*/Model1.ssdl|res://*/Model1.msl;provider=Npgsql;provider connection string=&quot;Host=localhost;Database=postgres;Username=postgres;Password=123&quot;" providerName="System.Data.EntityClient" /><add name="postgresEntities1" connectionString="metadata=res://*/Model1.csdl|res://*/Model1.ssdl|res://*/Model1.msl;provider=Npgsql;provider connection string=&quot;Host=localhost;Database=postgres;Username=postgres;Password=123;Persist Security Info=True&quot;" providerName="System.Data.EntityClient" /><add name="postgresEntities2" connectionString="metadata=res://*/Model1.csdl|res://*/Model1.ssdl|res://*/Model1.msl;provider=Npgsql;provider connection string=&quot;Host=localhost;Database=postgres;Username=postgres;Persist Security Info=True&quot;" providerName="System.Data.EntityClient" /><add name="postgresEntities3" connectionString="metadata=res://*/Model1.csdl|res://*/Model1.ssdl|res://*/Model1.msl;provider=Npgsql;provider connection string=&quot;Host=localhost;Database=postgres;Username=postgres;Password=123;Persist Security Info=True&quot;" providerName="System.Data.EntityClient" /></connectionStrings>
  <system.data>
    <DbProviderFactories>
       <remove invariant="Npgsql" />
      <add name="Npgsql Data Provider" invariant="Npgsql" description=".Net Data Provider for PostgreSQL" type="Npgsql.NpgsqlFactory, Npgsql, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7" support="FF" />
    <add name="dotConnect for PostgreSQL" invariant="Devart.Data.PostgreSql" description="Devart dotConnect for PostgreSQL" type="Devart.Data.PostgreSql.PgSqlProviderFactory, Devart.Data.PostgreSql, Version= 7.11.1190.0, Culture=neutral, PublicKeyToken=09af7300eec23701" /></DbProviderFactories>
  </system.data>`
`<system.web>
    <compilation debug="true" targetFramework="4.6.1" />
    <httpRuntime targetFramework="4.6.1" />
    <httpModules>
      <add name="ApplicationInsightsWebTracking" type="Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule, Microsoft.AI.Web" />
    </httpModules>
  </system.web>
`<providers>
     <provider invariantName="Devart.Data.PostgreSql" type="Devart.Data.PostgreSql.Entity.PgSqlEntityProviderServices, Devart.Data.PostgreSql.Entity.EF6, Version=7.11.1190.0, Culture=neutral, PublicKeyToken=09af7300eec23701" />
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
      <provider invariantName="Npgsql" type="Npgsql.NpgsqlServices, EntityFramework6.Npgsql" />
    <provider invariantName="MySql.Data.MySqlClient" type="MySql.Data.MySqlClient.MySqlProviderServices, MySql.Data.Entity.EF6, Version=6.10.7.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d">
      </provider></providers>`

**Comment by austindrenski** [comment]
@alibekp If you believe this to be an issue with Npgsql, could you please open this issue _in the Npgsql repository_?

**Comment by alibekp** [comment]
Opened issue in https://github.com/npgsql/npgsql/issues

**Comment by alibekp** [comment]
@austindrenski Opened issue in https://github.com/npgsql/npgsql/issues
